feat(scripts): redo the battery scripts (update related udev rules)

diff --git a/scripts/battery/batwarning b/scripts/battery/batwarning
--- a/scripts/battery/batwarning
+++ b/scripts/battery/batwarning
@@ -1,14 +1,53 @@
 #!/usr/bin/env bash
 
-# for the cron job
-export XDG_RUNTIME_DIR="/run/user/1000"
+[[ -z $SCRIPTS ]] && SCRIPTS="$HOME/.dotfiles/scripts"
+
+. "$SCRIPTS/battery/config.sh"
+. "$SCRIPTS/utils.sh"
+
+version=2.0.0
+
+LONGOPTS=help
+OPTIONS=h
+
+PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
+eval set -- "$PARSED"
+
+while true; do
+	case "$1" in
+	-h | --help)
+		echo -e ""
+		echo -e "  ${BOLD}Usage:${END_BOLD}    $(basename "$0") ${YELLOW}[${B_RED}options${DARK_GRAY}...${YELLOW}]${RESET}"
+		echo -e "  ${BOLD}Version:${RESET}  ${YELLOW}$version${RESET}"
+		echo -e ""
+		echo -e "  ${BOLD}Description:${RESET}"
+		echo -e ""
+		echo -e "    ${B_GRAY}Send a warning on defined battery levels.${RESET}"
+		echo -e ""
+		echo -e "  ${BOLD}Options:${RESET}"
+		echo -e ""
+		echo -e "    ${BLUE}-h${RESET}, ${BLUE}--help${RESET}       ${B_RED}-${RESET} Show this help and exit."
+		echo -e ""
+		echo -e "  ${BOLD}Examples:${RESET}"
+		echo -e ""
+		echo -e "    ${RED}\$${RESET} ${B_MAGENTA}$(basename "$0")${RESET}"
+		echo -e ""
+		exit 0
+		;;
+	--)
+		shift
+		break
+		;;
+	*)
+		echo -e "${RED}Error:${RESET} Programming error"
+		exit 3
+		;;
+	esac
+done
 
 BAT_CACHE_DIR=/tmp/battery
 LOW_NOTF_FILE="$BAT_CACHE_DIR/low"
 CHARGED_FILE="$BAT_CACHE_DIR/full"
-
-WARNING_LEVELS=(20 5 3)
-CHARGED_ON=95
 
 [[ ! -d "$BAT_CACHE_DIR" ]] && mkdir "$BAT_CACHE_DIR"
 [[ ! -f "$LOW_NOTF_FILE" ]] && touch "$LOW_NOTF_FILE"
@@ -17,8 +56,6 @@ current_percentage=$(acpi | grep -Po '[0-9]{1,3}(?=%)')
 is_discharging=$(acpi | grep -c "Discharging")
 
 notified_for=$(cat "$LOW_NOTF_FILE")
-
-NOTIFICATION_ID=4215
 
 if
 	[[ "$current_percentage" -ge "$CHARGED_ON" &&
